# Generated by Django 5.1 on 2024-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('backlog', 'backlog'), ('in process', 'in process'), ('completed', 'completed')], default='backlog', max_length=50),
        ),
    ]
