# Generated by Django 5.1 on 2024-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('Бэклог', 'Бэклог'), ('В процессе', 'В процессе'), ('Выполнено', 'Выполнено')], default='Бэклог', max_length=50),
        ),
    ]
