# Generated by Django 5.1 on 2024-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(default='default fio', max_length=150),
            preserve_default=False,
        ),
    ]
